wip feat: Add sme as Rc<RefCell<Executor<SM, P>>> to StateMachine
This compiles and the test runs, but if I enable line 426, the println!
that uses StateMachine::sme it fails with 'already mutably borrowed':

  thread 'test::test_sm_1s_no_enter_no_exit' panicked at 'already mutably borrowed: BorrowError', hsm0-executor/src/lib.rs:422:50

So this technique doesn't work :(

I'm thinking maybe I need to pass sme as a parameter to the state machine
entry, process and exit fn's.